---
- name: Generate systemd unit file for the container(s)
  containers.podman.podman_generate_systemd:
    name: dojo
    dest: ~/.config/systemd/user/
    restart_policy: on-failure
    restart_sec: 10

- name: Start the container(s) with systemd, so systemd will know the state of the container(s) moving forward.
  ansible.builtin.systemd:
    name: container-dojo
    scope: user
    state: started
  failed_when: false
